title: Rain's Dev Blog
description: > # this means to ignore newlines until "baseurl:"
  Rain's dev logging blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog !!! have to rebuild after modify this !!!
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Rain Byun # add your name
author-img: i-see-you.png # add your photo
about-author: Dev # add description
social-github: ragubyun # add your Github handle
social-email: ragubyun@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
